### ISSUE TITLE
How to further deal with study rooms?

### ISSUE THREAD

**Issue by oliverhummel** [informatik-mannheim/HSMA-CTT#236]
I think displaying the number of free study seats should be removed?

Ideally, we should not remove it fully, but make it configurable from the outside.

**Comment by Wifi-cable** [comment]
This issue is not fully a software problem. Talking to the University's administration is required. 

Suggestion: 
-Comment out the "Lernräume" (study rooms) link in the header at the index page.  
-Comment why this is done. 

If the administration decides to want the study room feature enabled again, we still have the code.
